/* tslint:disable */
/* eslint-disable */
/**
 * MVC Bridge API Spec
 * API definition for Mvc Bridge provided apis
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * The deposit address for the token.
 * @export
 * @interface DepositAddressResponse
 */
export interface DepositAddressResponse {
    /**
     * The deposit address for the token.
     * @type {string}
     * @memberof DepositAddressResponse
     */
    address?: string;
    /**
     * The public chain of your source address(mvc eth tron bsc ...)
     * @type {string}
     * @memberof DepositAddressResponse
     */
    chain?: string;
    /**
     * The token name you sent(usdt usdc ...)
     * @type {string}
     * @memberof DepositAddressResponse
     */
    tokenName?: string;
}
/**
 * Register a bridging request.
 * @export
 * @interface OrderRegisterRequest
 */
export interface OrderRegisterRequest {
    /**
     * The public chain of your source address(mvc eth tron bsc ...)
     * @type {string}
     * @memberof OrderRegisterRequest
     */
    fromChain?: string;
    /**
     * The token name you sent(usdt usdc ...)
     * @type {string}
     * @memberof OrderRegisterRequest
     */
    fromTokenName?: string;
    /**
     * The transaction of your sending request. Must be found on the blockchain to proceed.
     * @type {string}
     * @memberof OrderRegisterRequest
     */
    txid?: string;
    /**
     * Amount you send, use String for large values.
     * @type {string}
     * @memberof OrderRegisterRequest
     */
    amount?: string;
    /**
     * The address from which you send your tx. Must be valid source in the transaction.
     * @type {string}
     * @memberof OrderRegisterRequest
     */
    fromAddress?: string;
    /**
     * The public chain you want to bridge your asset to (mvc eth tron bsc ...).
     * @type {string}
     * @memberof OrderRegisterRequest
     */
    toChain?: string;
    /**
     * The token name you want to receive(usdt usdc ...)
     * @type {string}
     * @memberof OrderRegisterRequest
     */
    toTokenName?: string;
    /**
     * The address you want to bridge your asset to.
     * @type {string}
     * @memberof OrderRegisterRequest
     */
    toAddress?: string;
    /**
     * The signature indicating you are the owner of fromAddress.
     * @type {string}
     * @memberof OrderRegisterRequest
     */
    signature?: string;
}
/**
 * 
 * @export
 * @interface OrderRegisterResp
 */
export interface OrderRegisterResp {
    /**
     * The txid of your request.
     * @type {string}
     * @memberof OrderRegisterResp
     */
    orderTxid?: string;
    /**
     * True if registered successful.
     * @type {boolean}
     * @memberof OrderRegisterResp
     */
    success?: boolean;
    /**
     * The reason of your failed request.
     * @type {string}
     * @memberof OrderRegisterResp
     */
    message?: string;
}
/**
 * The deposits waiting for request to confirm target.
 * @export
 * @interface OrderWaiting
 */
export interface OrderWaiting {
    /**
     * The vault id of your request.
     * @type {string}
     * @memberof OrderWaiting
     */
    vaultId?: string;
    /**
     * The txid of your request.
     * @type {string}
     * @memberof OrderWaiting
     */
    txid?: string;
    /**
     * The address from which you send your tx. Must be valid source in the transaction.
     * @type {string}
     * @memberof OrderWaiting
     */
    fromAddress?: string;
    /**
     * Amount you sent, use String for large values.
     * @type {string}
     * @memberof OrderWaiting
     */
    fromAmount?: string;
}

/**
 * OrderApi - axios parameter creator
 * @export
 */
export const OrderApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get the deposits waiting for request.
         * @param {string} fromChain The public chain of your source address(mvc eth tron bsc ...)
         * @param {string} fromTokenName The token name you sent(usdt usdc ...)
         * @param {string} address The address from which you send your tx. Must be valid source in the transaction.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderFromChainFromTokenNameAddressWaitingGet: async (fromChain: string, fromTokenName: string, address: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'fromChain' is not null or undefined
            if (fromChain === null || fromChain === undefined) {
                throw new RequiredError('fromChain','Required parameter fromChain was null or undefined when calling orderFromChainFromTokenNameAddressWaitingGet.');
            }
            // verify required parameter 'fromTokenName' is not null or undefined
            if (fromTokenName === null || fromTokenName === undefined) {
                throw new RequiredError('fromTokenName','Required parameter fromTokenName was null or undefined when calling orderFromChainFromTokenNameAddressWaitingGet.');
            }
            // verify required parameter 'address' is not null or undefined
            if (address === null || address === undefined) {
                throw new RequiredError('address','Required parameter address was null or undefined when calling orderFromChainFromTokenNameAddressWaitingGet.');
            }
            const localVarPath = `/order/{fromChain}/{fromTokenName}/{address}/waiting`
                .replace(`{${"fromChain"}}`, encodeURIComponent(String(fromChain)))
                .replace(`{${"fromTokenName"}}`, encodeURIComponent(String(fromTokenName)))
                .replace(`{${"address"}}`, encodeURIComponent(String(address)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get the deposit address for the token.
         * @param {string} fromChain The public chain of your source address(mvc eth tron bsc ...)
         * @param {string} fromTokenName The token name you sent(usdt usdc ...)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderFromChainFromTokenNameDepositAddressGet: async (fromChain: string, fromTokenName: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'fromChain' is not null or undefined
            if (fromChain === null || fromChain === undefined) {
                throw new RequiredError('fromChain','Required parameter fromChain was null or undefined when calling orderFromChainFromTokenNameDepositAddressGet.');
            }
            // verify required parameter 'fromTokenName' is not null or undefined
            if (fromTokenName === null || fromTokenName === undefined) {
                throw new RequiredError('fromTokenName','Required parameter fromTokenName was null or undefined when calling orderFromChainFromTokenNameDepositAddressGet.');
            }
            const localVarPath = `/order/{fromChain}/{fromTokenName}/deposit/address`
                .replace(`{${"fromChain"}}`, encodeURIComponent(String(fromChain)))
                .replace(`{${"fromTokenName"}}`, encodeURIComponent(String(fromTokenName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Register a new order to the bridge.
         * @param {OrderRegisterRequest} [orderRegisterRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderRegisterPost: async (orderRegisterRequest?: OrderRegisterRequest, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/order/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const nonString = typeof orderRegisterRequest !== 'string';
            const needsSerialization = nonString && configuration && configuration.isJsonMime
                ? configuration.isJsonMime(localVarRequestOptions.headers['Content-Type'])
                : nonString;
            localVarRequestOptions.data =  needsSerialization
                ? JSON.stringify(orderRegisterRequest !== undefined ? orderRegisterRequest : {})
                : (orderRegisterRequest || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OrderApi - functional programming interface
 * @export
 */
export const OrderApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get the deposits waiting for request.
         * @param {string} fromChain The public chain of your source address(mvc eth tron bsc ...)
         * @param {string} fromTokenName The token name you sent(usdt usdc ...)
         * @param {string} address The address from which you send your tx. Must be valid source in the transaction.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async orderFromChainFromTokenNameAddressWaitingGet(fromChain: string, fromTokenName: string, address: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<OrderWaiting>>> {
            const localVarAxiosArgs = await OrderApiAxiosParamCreator(configuration).orderFromChainFromTokenNameAddressWaitingGet(fromChain, fromTokenName, address, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get the deposit address for the token.
         * @param {string} fromChain The public chain of your source address(mvc eth tron bsc ...)
         * @param {string} fromTokenName The token name you sent(usdt usdc ...)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async orderFromChainFromTokenNameDepositAddressGet(fromChain: string, fromTokenName: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DepositAddressResponse>> {
            const localVarAxiosArgs = await OrderApiAxiosParamCreator(configuration).orderFromChainFromTokenNameDepositAddressGet(fromChain, fromTokenName, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Register a new order to the bridge.
         * @param {OrderRegisterRequest} [orderRegisterRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async orderRegisterPost(orderRegisterRequest?: OrderRegisterRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrderRegisterResp>> {
            const localVarAxiosArgs = await OrderApiAxiosParamCreator(configuration).orderRegisterPost(orderRegisterRequest, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * OrderApi - factory interface
 * @export
 */
export const OrderApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Get the deposits waiting for request.
         * @param {string} fromChain The public chain of your source address(mvc eth tron bsc ...)
         * @param {string} fromTokenName The token name you sent(usdt usdc ...)
         * @param {string} address The address from which you send your tx. Must be valid source in the transaction.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderFromChainFromTokenNameAddressWaitingGet(fromChain: string, fromTokenName: string, address: string, options?: any): AxiosPromise<Array<OrderWaiting>> {
            return OrderApiFp(configuration).orderFromChainFromTokenNameAddressWaitingGet(fromChain, fromTokenName, address, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get the deposit address for the token.
         * @param {string} fromChain The public chain of your source address(mvc eth tron bsc ...)
         * @param {string} fromTokenName The token name you sent(usdt usdc ...)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderFromChainFromTokenNameDepositAddressGet(fromChain: string, fromTokenName: string, options?: any): AxiosPromise<DepositAddressResponse> {
            return OrderApiFp(configuration).orderFromChainFromTokenNameDepositAddressGet(fromChain, fromTokenName, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Register a new order to the bridge.
         * @param {OrderRegisterRequest} [orderRegisterRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderRegisterPost(orderRegisterRequest?: OrderRegisterRequest, options?: any): AxiosPromise<OrderRegisterResp> {
            return OrderApiFp(configuration).orderRegisterPost(orderRegisterRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OrderApi - object-oriented interface
 * @export
 * @class OrderApi
 * @extends {BaseAPI}
 */
export class OrderApi extends BaseAPI {
    /**
     * 
     * @summary Get the deposits waiting for request.
     * @param {string} fromChain The public chain of your source address(mvc eth tron bsc ...)
     * @param {string} fromTokenName The token name you sent(usdt usdc ...)
     * @param {string} address The address from which you send your tx. Must be valid source in the transaction.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrderApi
     */
    public orderFromChainFromTokenNameAddressWaitingGet(fromChain: string, fromTokenName: string, address: string, options?: any) {
        return OrderApiFp(this.configuration).orderFromChainFromTokenNameAddressWaitingGet(fromChain, fromTokenName, address, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get the deposit address for the token.
     * @param {string} fromChain The public chain of your source address(mvc eth tron bsc ...)
     * @param {string} fromTokenName The token name you sent(usdt usdc ...)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrderApi
     */
    public orderFromChainFromTokenNameDepositAddressGet(fromChain: string, fromTokenName: string, options?: any) {
        return OrderApiFp(this.configuration).orderFromChainFromTokenNameDepositAddressGet(fromChain, fromTokenName, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Register a new order to the bridge.
     * @param {OrderRegisterRequest} [orderRegisterRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrderApi
     */
    public orderRegisterPost(orderRegisterRequest?: OrderRegisterRequest, options?: any) {
        return OrderApiFp(this.configuration).orderRegisterPost(orderRegisterRequest, options).then((request) => request(this.axios, this.basePath));
    }
}


